name: Run Tests and build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MAILJET_API: ${{ secrets.MAILJET_API }}
      MAILJET_SECRET: ${{ secrets.MAILJET_SECRET}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        if: success()
        run: npm run build

      - name: Display size of dist directory
        if: success()
        run: du -sh dist
